POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTc2OTMyNDIsInVzZXJJZCI6MX0.lBpIzo6LymTA-IqUaPRUUFn3WZxSoeV8juHQ4mzMvE8

{
  "name": "Test eventt",
  "description": "test event!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
